### ISSUE TITLE
Upgrade 1.7 Common Component: kubeflow-knative

### ISSUE THREAD

**Issue by wg102** [StatCan/kubeflow-manifest#349]
No visible adjustements

## Testing

Usually a good idea to make sure all of the overrides are working is to run the following command and verify all  the yaml output for the component is what you expect and all of the overrides are taken into account.

- The kubeflow-namespace Namespace is patched correctly (removed label)

```sh
task stack:aaw:preview
```

**Note**: The command above will render all of the manifests into manifests top level folder with the name `aaw.yaml`. A trick to keep the yaml output small is under `stacks/aaw/kustomization.yaml` to only have the component you wish to test referenced.

**Comment by Jose-Matsuda** [comment]
WIP comment
```
  name: config-istio
  namespace: knative-serving
```

In our kustomize we have 
```
  gateway.ingress-general-system.general-istio-ingress-gateway-https: general.ingress-general-system.svc.cluster.local
  local-gateway.istio-system.cluster-local-gateway: cluster-local-gateway.istio-system.svc.cluster.local
  local-gateway.mesh: mesh
```
 which is fine, but when I check the output I see 
```
  gateway.ingress-general-system.general-istio-ingress-gateway-https: general.ingress-general-system.svc.cluster.local
  gateway.kubeflow.kubeflow-gateway: istio-ingressgateway.istio-system.svc.cluster.local
  local-gateway.istio-system.cluster-local-gateway: cluster-local-gateway.istio-system.svc.cluster.local
  local-gateway.mesh: mesh
```
with the important bit being the `gateway.kubeflow` because I see in a comment a few lines above ` # This is commented out as we don't want it exposed on the gateway since the authenticaion only works for kubeflow`.

Do note that this also still matches what we currently have on the cluster.
![image](https://github.com/StatCan/aaw-kubeflow-manifests/assets/23174198/62049abb-711c-48a9-ab81-d52a966a8f6e)
